### ISSUE TITLE
Babel is missing

### ISSUE THREAD

**Issue by AlexDCryptoC** [Loopring/circulr#165]
Hi,

I just cloned your repo, i followed all the necessary steps in order to install and run the app with both npm install (first npm install in the main directory and the second npm install in src/common....) and after that, while i tried to run "npm run start", i received the next error:
 [BABEL] /var/www/project/dexlabexchange/circulr/.webpackrc.js: The pipeline operator plugin requires a 'proposal' option.'proposal' must be one of: minimal. More details: https://babeljs.io/docs/en/next/babel-plugin-proposal-pipeline-operator (While processing: "/var/www/project/dexlabexchange/circulr/node_modules/@babel/plugin-proposal-pipeline-operator/lib/index.js$inherits").

On that website where the error is redirecting me i found a possible solution but also with that script it doesn't work...

Could you please help me?

best regards Alex D.

**Comment by xyths** [comment]
i got the same error. i reinstall the roadhog, and it works.
```
npm uninstall roadhog
npm install roadhog
```

**Comment by AlexDCryptoC** [comment]
Solved by updating the Babel version to 2.4
